// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzuygijasogagyduwrns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6dXlnaWphc29nYWd5ZHV3cm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg0NTUyMjYsImV4cCI6MjEwNDAzMTIyNn0.QgE4TRv0kLxD-0Ye4SiWrNoqgrkUJRPgpH1B2uC9VjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});